### ISSUE TITLE
Failed to compile on Linux Mint (could not compile shukusai)

### ISSUE THREAD

**Issue by vitali2y** [hinto-janai/festival#19]
## OS & Version
```
➜  festival git:(main) grep PRETTY_NAME /etc/os-release 
PRETTY_NAME="Linux Mint 21"
➜  festival git:(main) rustc -V                                                                                                                            
rustc 1.68.2 (9eb3afe9e 2023-03-27)
➜  festival git:(main)
```

## Bug
```
➜  my_rust git clone --recursive https://github.com/hinto-janai/festival && cd festival && cargo build --release
Cloning into 'festival'...
~...~
   Compiling shukusai v0.0.1 (/home/vit/prjs/my_rust/festival/shukusai)
   Compiling clap v4.3.8
   Compiling dirs v5.0.1
   Compiling egui-notify v0.7.0 (/home/vit/prjs/my_rust/festival/external/egui-notify)
warning: the item `Seek` is imported redundantly
   --> shukusai/src/audio/audio.rs:441:7
    |
21  |         Volume,Append,Repeat,Seek,
    |                              ---- the item `Seek` is already imported here
...
441 |         use crate::audio::Seek;
    |             ^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_imports)]` on by default

error[E0599]: no function or associated item named `into_inner` found for struct `Arc<_>` in the current scope
   --> shukusai/src/ccd/ccd.rs:119:28
    |
119 |                     if let Some(c) = Arc::into_inner(old_collection) {
    |                                           ^^^^^^^^^^ function or associated item not found in `Arc<_>`

warning: unused import: `Json`
  --> shukusai/src/kernel/kernel.rs:27:21
   |
27 | use disk::{Bincode2,Json};
   |                     ^^^^

For more information about this error, try `rustc --explain E0599`.
warning: `shukusai` (lib) generated 2 warnings
error: could not compile `shukusai` due to previous error; 2 warnings emitted
➜  festival git:(main)
```

## Steps
Just cloned recursively and started to build in release mode according to [build](https://github.com/hinto-janai/festival#build) instructions, but failed with compilation error as above.

**Comment by hinto-janai** [comment]
`Arc::into_inner()` was stabilized in Rust 1.70, you'll have to `rustup update`.

**Comment by vitali2y** [comment]
Yep, after updating to 1.70.0 all seems well, thank you.
